# Generated by Django 4.0.3 on 2022-04-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Elden Ring', 'Elden Ring'), ('Tekken', 'Tekken'), ('Games', 'Games')], default='Choose category', max_length=50),
        ),
    ]
